# Generated by Django 4.2.3 on 2023-07-19 21:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_age_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, null=True, region=None
            ),
        ),
    ]
