# Generated by Django 4.2.2 on 2023-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NONE", "Not categorized yet"),
                            ("ELEC", "Electronics"),
                            ("FASH", "Fashion and Apprael"),
                            ("HOME", "Home and Kitchen"),
                        ],
                        default="NONE",
                        max_length=4,
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
    ]
