# Generated by Django 4.2.3 on 2023-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
