# Generated by Django 4.2.3 on 2023-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_orderproduct_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
