# Generated by Django 4.2.3 on 2023-07-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/products/"
            ),
        ),
    ]
